#! /usr/bin/python3.6
# Unit tests relating to Tapestry. Current as of 2.0.
# See the documentation - there are dependancies

# Import Block
from datetime import date
from Development.Source import dev
from Development.Testing import framework as fw

# Extra Classes Go Here

# Define Tests As Functions Here
'''This test compares the known-good RIFF (namespace.goodRIFF) to an RIFF
    generated by importing the corresponding function from Tapestry itself
    and providing dummy arguments.
'''
def test_RIFF_compliance(namespace):
    pass

# Declare Some Constants

ns = type('',(),{})()  # We need a general-purpose namespace object
ns.key_sign_fp = 0 # TODO input
ns.key_crypt_fp = 0 # TODO input
ns.goodRIFF = 0 # TODO Generate and Encode
ns.filename = "unit_test-"+str(ns.uid)+"-"+str(date.today())+".log"
ns.logger = fw.simpleLogger("Logs",ns.filename,"unit-tests")
